import Head from "next/head";
import styled from "@emotion/styled";

const BodyContainer = styled.main`
    margin: 0 auto;
`;
const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Envited Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BodyContainer>{children}</BodyContainer>
    </>
  );
};

export default Layout;
